### ISSUE TITLE
微信版本适配

### ISSUE THREAD

**Issue by jauzzz** [eritpchy/Xposed-Fingerprint-pay#1]
plau版微信6.5.10并不生效，请求作者大大适配

**Comment by eritpchy** [comment]
6.5.13 版已经有了 希望你直接用上新版

**Comment by jauzzz** [comment]
@eritpchy 需要等其他微信插件适配13，其实我是想问，play版的微信(也有13了)是否支持，play的淘宝支付宝都没问题。

**Comment by eritpchy** [comment]
只要和我上传的版本6.15.13  1100  基本一致 一般是没问题的

**Comment by eritpchy** [comment]
我没有play 我也不用play

**Comment by jauzzz** [comment]
明白啦，感谢:smile:

**Comment by jauzzz** [comment]
可以close啦
