### ISSUE TITLE
不支持play版微信6.5.16.1101

### ISSUE THREAD

**Issue by liaobin** [eritpchy/Xposed-Fingerprint-pay#10]
还望更新

**Comment by 1209079611** [comment]
是的，能适配6.5.16play版吗

**Comment by eritpchy** [comment]
计划中

**Comment by eritpchy** [comment]
Fixed https://github.com/eritpchy/Xposed-Fingerprint-pay/commit/116d5dda16f3b19078fefd0df1d489f92ffe6960
