### ISSUE TITLE
微信6.5.16 1120 版无效

### ISSUE THREAD

**Issue by wyagd001** [eritpchy/Xposed-Fingerprint-pay#13]
红米note4x 7.0系统 最新xposed 88.2 test4，微信无效。
最新支付宝有效。

**Comment by eritpchy** [comment]
请打开微信 支付界面后上传Xposed 日志

**Comment by wyagd001** [comment]
10-18 20:33:19.884 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.ui.LauncherUI@3be39b3	
10-18 20:33:20.100 I/Xposed  ( 3558): WeChatFp [handleLoadPackage](WalletBaseUI.java:34) loaded: [com.tencent.mm] version:2.3.0
10-18 20:33:20.137 I/Xposed  ( 3558): Found wechat version:6.5.16
10-18 20:33:24.771 E/Xposed  ( 3609): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.providers.downloads.DownloadJobService
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at com.ceco.nougat.gravitybox.ModDownloadProvider.init(ModDownloadProvider.java:45)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at com.ceco.nougat.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:216)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:123)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1574)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at android.os.Looper.loop(Looper.java:163)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at android.app.ActivityThread.main(ActivityThread.java:6237)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at java.lang.reflect.Method.invoke(Native Method)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:111)
10-18 20:33:24.771 E/Xposed  ( 3609): Caused by: java.lang.ClassNotFoundException: com.android.providers.downloads.DownloadJobService
10-18 20:33:24.771 E/Xposed  ( 3609): 	at java.lang.Class.classForName(Native Method)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at java.lang.Class.forName(Class.java:400)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:67)
10-18 20:33:24.771 E/Xposed  ( 3609): 	... 17 more
10-18 20:33:24.771 E/Xposed  ( 3609): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.downloads.DownloadJobService" on path: DexPathList[[zip file "/system/framework/cloud-common.jar", zip file "/system/priv-app/DownloadProvider/DownloadProvider.apk"],nativeLibraryDirectories=[/system/priv-app/DownloadProvider/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
10-18 20:33:24.771 E/Xposed  ( 3609): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
10-18 20:33:24.771 E/Xposed  ( 3609): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-18 20:33:24.771 E/Xposed  ( 3609): 	... 21 more
10-18 20:33:25.165 I/Xposed  ( 3558): WeChatFp [beforeHookedMethod](WalletBaseUI.java:38) Application onCreate
10-18 20:33:25.167 I/Xposed  ( 3558): WeChatFp [main](XposedWeChatPlugin.java:63) Xposed plugin init version: 2.3.0
10-18 20:33:25.576 I/Xposed  ( 3609): Specher com.android.providers.media调用stopSelf
10-18 20:33:25.576 I/Xposed  ( 3609): Specher com.android.providers.downloads调用stopSelf
10-18 20:33:25.613 I/Xposed  ( 3609): Specher com.android.providers.media调用stopSelf
10-18 20:33:25.613 I/Xposed  ( 3609): Specher com.android.providers.downloads调用stopSelf
10-18 20:33:25.628 I/Xposed  ( 3609): Specher com.android.providers.media调用stopSelf
10-18 20:33:25.628 I/Xposed  ( 3609): Specher com.android.providers.downloads调用stopSelf
10-18 20:33:25.668 I/Xposed  ( 3609): Specher com.android.providers.media调用stopSelf
10-18 20:33:25.668 I/Xposed  ( 3609): Specher com.android.providers.downloads调用stopSelf
10-18 20:33:26.816 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.mall.ui.MallIndexUI@f6d2d4f	
10-18 20:33:29.400 I/Xposed  ( 3609): Specher com.android.providers.media调用stopSelf
10-18 20:33:29.400 I/Xposed  ( 3609): Specher com.android.providers.downloads调用stopSelf
10-18 20:33:29.525 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:33:29.525 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:33:29.723 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.offline.ui.WalletOfflineCoinPurseUI@f7509e1	
10-18 20:33:35.787 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:33:35.787 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:33:35.958 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.wallet_core.ui.WalletCheckPwdUI@6c3d283	
10-18 20:33:43.139 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:33:43.139 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:33:43.218 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:33:43.218 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:33:43.676 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.offline.ui.WalletOfflineCoinPurseUI@25783c4	
10-18 20:33:52.546 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:33:52.546 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:33:52.602 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.mall.ui.MallIndexUI@f6d2d4f	
10-18 20:33:52.686 I/Xposed  ( 1612): Specher com.android.server.telecom调用killProcessQuiet
10-18 20:33:52.689 I/Xposed  ( 1612): Specher com.dsi.ant.server调用killProcessQuiet
10-18 20:33:52.690 I/Xposed  ( 1612): Specher android调用killProcessQuiet
10-18 20:33:52.691 I/Xposed  ( 1612): Specher com.android.providers.settings调用killProcessQuiet
10-18 20:33:52.693 I/Xposed  ( 1612): Specher com.qualcomm.location调用killProcessQuiet
10-18 20:33:59.289 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:33:59.289 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:33:59.327 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.ui.LauncherUI@3be39b3	
10-18 20:33:59.515 I/Xposed  ( 3979): WeChatFp [handleLoadPackage](WalletBaseUI.java:34) loaded: [com.tencent.mm] version:2.3.0
10-18 20:33:59.550 I/Xposed  ( 3979): Found wechat version:6.5.16
10-18 20:34:01.654 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.setting.ui.setting.SettingsUI@72665e1	
10-18 20:34:04.447 I/Xposed  ( 3979): WeChatFp [beforeHookedMethod](WalletBaseUI.java:38) Application onCreate
10-18 20:34:04.509 I/Xposed  ( 3979): WeChatFp [main](XposedWeChatPlugin.java:63) Xposed plugin init version: 2.3.0
10-18 20:34:09.434 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.445 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.501 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.507 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.509 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.513 I/Xposed  ( 2823): Specher com.xiaomi.xmsf调用stopSelf
10-18 20:34:09.514 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.516 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.573 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.585 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:09.650 I/Xposed  ( 4142): Specher com.miui.video调用stopSelf
10-18 20:34:45.966 I/Xposed  ( 1612): Specher com.android.server.telecom调用killProcessQuiet
10-18 20:34:45.969 I/Xposed  ( 1612): Specher com.dsi.ant.server调用killProcessQuiet
10-18 20:34:45.971 I/Xposed  ( 1612): Specher android调用killProcessQuiet
10-18 20:34:45.974 I/Xposed  ( 1612): Specher com.android.providers.settings调用killProcessQuiet
10-18 20:34:45.976 I/Xposed  ( 1612): Specher com.qualcomm.location调用killProcessQuiet
10-18 20:35:11.846 I/Xposed  ( 4388): WeChatFp [handleLoadPackage](WalletBaseUI.java:34) loaded: [com.tencent.mm] version:2.3.0
10-18 20:35:11.878 I/Xposed  ( 4388): Found wechat version:6.5.16
10-18 20:35:14.559 I/Xposed  ( 4267): Specher de.robv.android.xposed.installer调用killProcess
10-18 20:35:14.559 I/Xposed  ( 4267): Specher com.miui.contentcatcher调用killProcess
10-18 20:35:15.397 I/Xposed  ( 4419): Specher com.miui.bugreport调用stopSelf
10-18 20:35:15.397 I/Xposed  ( 4419): Specher com.miui.contentcatcher调用stopSelf
10-18 20:35:16.383 I/Xposed  ( 4388): Specher com.tencent.mm调用stopSelf
10-18 20:35:32.336 I/Xposed  ( 4419): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:35:32.336 I/Xposed  ( 4419): Specher com.miui.bugreport调用Acitvity.finish
10-18 20:35:32.895 I/Xposed  ( 4419): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:35:32.895 I/Xposed  ( 4419): Specher com.miui.bugreport调用Acitvity.finish
10-18 20:35:35.154 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.setting.ui.setting.SettingsUI@72665e1	
10-18 20:35:35.294 I/Xposed  ( 4495): WeChatFp [handleLoadPackage](WalletBaseUI.java:34) loaded: [com.tencent.mm] version:2.3.0
10-18 20:35:35.327 I/Xposed  ( 4495): Found wechat version:6.5.16
10-18 20:35:37.225 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.setting.ui.setting.SettingsAccountInfoUI@8afe788	
10-18 20:35:38.241 I/Xposed  (12378): Specher com.tencent.mm调用Acitvity.finish
10-18 20:35:38.242 I/Xposed  (12378): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:35:38.282 I/Xposed  (12378): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:81) Activity onResume =	com.tencent.mm.plugin.setting.ui.setting.SettingsUI@72665e1	
10-18 20:35:40.172 I/Xposed  ( 4495): WeChatFp [beforeHookedMethod](WalletBaseUI.java:38) Application onCreate
10-18 20:35:40.173 I/Xposed  ( 4495): WeChatFp [main](XposedWeChatPlugin.java:63) Xposed plugin init version: 2.3.0
10-18 20:35:40.789 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:40.795 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:40.949 I/Xposed  ( 4565): WeChatFp [handleLoadPackage](WalletBaseUI.java:44) loaded: [com.eg.android.AlipayGphone] version:2.3.0
10-18 20:35:41.216 I/Xposed  ( 4565): WeChatFp [beforeHookedMethod](WalletBaseUI.java:48) Application onCreate
10-18 20:35:41.232 I/Xposed  ( 4565): WeChatFp [main](XposedAlipayPlugin.java:62) Xposed plugin init version: 2.3.0
10-18 20:35:41.247 I/Xposed  ( 4565): WeChatFp [main](XposedAlipayPlugin.java:68) app info: versionCode:115 versionName:10.1.2.091816
10-18 20:35:41.458 I/Xposed  ( 4659): WeChatFp [handleLoadPackage](WalletBaseUI.java:44) loaded: [com.eg.android.AlipayGphone] version:2.3.0
10-18 20:35:41.698 I/Xposed  ( 7615): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:41.699 I/Xposed  ( 7615): Specher com.google.android.webview调用stopSelf
10-18 20:35:41.699 I/Xposed  ( 7615): Specher com.miui.contentcatcher调用stopSelf
10-18 20:35:41.728 I/Xposed  ( 4659): WeChatFp [beforeHookedMethod](WalletBaseUI.java:48) Application onCreate
10-18 20:35:41.729 I/Xposed  ( 4659): WeChatFp [main](XposedAlipayPlugin.java:62) Xposed plugin init version: 2.3.0
10-18 20:35:41.743 I/Xposed  ( 4659): WeChatFp [main](XposedAlipayPlugin.java:68) app info: versionCode:115 versionName:10.1.2.091816
10-18 20:35:41.820 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:41.866 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:41.939 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:42.161 I/Xposed  ( 7615): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:35:42.161 I/Xposed  ( 7615): Specher com.eg.android.AlipayGphone调用Acitvity.finish
10-18 20:35:42.161 I/Xposed  ( 7615): Specher com.google.android.webview调用Acitvity.finish
10-18 20:35:42.269 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:42.779 I/Xposed  ( 7615): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:42.779 I/Xposed  ( 7615): Specher com.google.android.webview调用stopSelf
10-18 20:35:42.779 I/Xposed  ( 7615): Specher com.miui.contentcatcher调用stopSelf
10-18 20:35:48.176 I/Xposed  ( 7615): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:35:48.176 I/Xposed  ( 7615): Specher com.eg.android.AlipayGphone调用Acitvity.finish
10-18 20:35:48.176 I/Xposed  ( 7615): Specher com.google.android.webview调用Acitvity.finish
10-18 20:35:48.311 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:50.369 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:53.795 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:53.882 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.195 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.263 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.332 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.396 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.459 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.466 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.534 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.613 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.687 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.759 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.810 I/Xposed  (20850): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:54.831 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:55.161 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:55.230 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:55.300 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:55.370 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:35:55.449 I/Xposed  ( 4659): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:36:18.798 I/Xposed  ( 1612): Specher com.android.server.telecom调用killProcessQuiet
10-18 20:36:18.802 I/Xposed  ( 1612): Specher com.dsi.ant.server调用killProcessQuiet
10-18 20:36:18.810 I/Xposed  ( 1612): Specher android调用killProcessQuiet
10-18 20:36:18.816 I/Xposed  ( 1612): Specher com.android.providers.settings调用killProcessQuiet
10-18 20:36:18.820 I/Xposed  ( 1612): Specher com.qualcomm.location调用killProcessQuiet
10-18 20:36:19.843 I/Xposed  ( 3703): Specher com.miui.analytics调用stopSelf
10-18 20:36:54.250 I/Xposed  ( 5467): WeChatFp [handleLoadPackage](WalletBaseUI.java:44) loaded: [com.eg.android.AlipayGphone] version:2.3.0
10-18 20:36:54.405 I/Xposed  ( 5467): WeChatFp [beforeHookedMethod](WalletBaseUI.java:48) Application onCreate
10-18 20:36:54.407 I/Xposed  ( 5467): WeChatFp [main](XposedAlipayPlugin.java:62) Xposed plugin init version: 2.3.0
10-18 20:36:54.417 I/Xposed  ( 5467): WeChatFp [main](XposedAlipayPlugin.java:68) app info: versionCode:115 versionName:10.1.2.091816
10-18 20:36:54.968 I/Xposed  ( 5467): Specher com.eg.android.AlipayGphone调用stopSelf
10-18 20:36:59.851 I/Xposed  ( 1612): Specher com.android.server.telecom调用killProcessQuiet
10-18 20:36:59.853 I/Xposed  ( 1612): Specher com.dsi.ant.server调用killProcessQuiet
10-18 20:36:59.855 I/Xposed  ( 1612): Specher android调用killProcessQuiet
10-18 20:36:59.857 I/Xposed  ( 1612): Specher com.android.providers.settings调用killProcessQuiet
10-18 20:36:59.859 I/Xposed  ( 1612): Specher com.qualcomm.location调用killProcessQuiet
10-18 20:37:17.798 I/Xposed  ( 3703): Specher com.miui.analytics调用stopSelf
10-18 20:37:29.993 I/Xposed  ( 5764): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:37:29.993 I/Xposed  ( 5764): Specher system调用Acitvity.finish
10-18 20:37:31.368 I/Xposed  ( 5764): Specher com.miui.contentcatcher调用Acitvity.finish
10-18 20:37:31.368 I/Xposed  ( 5764): Specher system调用Acitvity.finish
10-18 20:37:39.317 I/Xposed  ( 1612): Specher com.android.server.telecom调用killProcessQuiet
10-18 20:37:39.321 I/Xposed  ( 1612): Specher com.dsi.ant.server调用killProcessQuiet
10-18 20:37:39.325 I/Xposed  ( 1612): Specher android调用killProcessQuiet
10-18 20:37:39.330 I/Xposed  ( 1612): Specher com.android.providers.settings调用killProcessQuiet
10-18 20:37:39.334 I/Xposed  ( 1612): Specher com.qualcomm.location调用killProcessQuiet

**Comment by eritpchy** [comment]
有几点需要重新确认
1. 你手机上的微信是否是我上传的版本? 而不是外面随便下载的
2. 这个指纹插件是否正常工作过? 如果是? 什么不一样了呢?
3. 请录制个简短的视频, 包含打开设置页面以及 进入输入支付密码页面
4. 上面都做完了吧Xposed日志(完整的)再发一遍

**Comment by wyagd001** [comment]
1.微信  酷安下载的最新版
2.指纹支付，最新的支付宝可以正常使用

**Comment by eritpchy** [comment]
你都不弄了
