### ISSUE TITLE
建议修改xxx版本不支持的显示方式

### ISSUE THREAD

**Issue by Cyanogen-Mod** [eritpchy/Xposed-Fingerprint-pay#14]
RT, 2.3.0版本的App, 遇到不支持的微信6.5.16-1101版本时, 会一直持续以Toast通知的形式提醒不支持
当前提醒方式会让人心烦…  建议修改成只发送一次Toast/通知栏消息.

**Comment by eritpchy** [comment]
麻烦不值得改

**Comment by Cyanogen-Mod** [comment]
好吧 😂😂😂
