### ISSUE TITLE
双开微信只有一个能用指纹支付

### ISSUE THREAD

**Issue by wanzhiyu** [eritpchy/Xposed-Fingerprint-pay#17]
如题，我是用的华为自带的应用双开来双开的微信，结果只有双开出来的那个微信才可以用指纹支付，原本的那个微信却不可以用指纹支付，请问是我哪里设置不对吗？

**Comment by eritpchy** [comment]
Testing...

**Comment by eritpchy** [comment]
三星S8已支持, 华为, 咳咳..

**Comment by eritpchy** [comment]
Fixed https://github.com/eritpchy/Xposed-Fingerprint-pay/commit/04a8e09ea6b32b94d35d9da640b27946440d0326
