### ISSUE TITLE
旧版本Play的支付宝和微信 能否提交支持?

### ISSUE THREAD

**Issue by WanderMax** [eritpchy/Xposed-Fingerprint-pay#18]
如题, 支付宝这东西越来越大所以还在用旧版, 能否提交支持?
目前是9.6.8.053103 Play版本.
其次, 能否搞一个脚本, 方便提取不同版本配置信息给你.
谢谢

**Comment by eritpchy** [comment]
请先自行测试

**Comment by WanderMax** [comment]
昨晚试过2.5版本, ,未提示不支持, 但是未找到指纹设置.
其次, 对于不支持的位置,会提示很多次...

**Comment by eritpchy** [comment]
2.5请测试支付宝
2.6 请测试微信

**Comment by WanderMax** [comment]
2.5版本 在支付宝中未找到指纹设置
2.6 版本?

**Comment by eritpchy** [comment]
那就是不支持， 清加群下载测试版

**Comment by WanderMax** [comment]
OK
再就是能否添加诸如 隐藏图标, 单独的支付支持开关, 比如我暂时不需要微信支持, 会弹窗显示不支持.

**Comment by eritpchy** [comment]
难， 不做！

**Comment by eritpchy** [comment]
用最新版没有不支持的说法

**Comment by WanderMax** [comment]
国产毒瘤 实在是不敢用最新版...

**Comment by eritpchy** [comment]
请用最新版
