### ISSUE TITLE
不支持play版微信6.5.13

### ISSUE THREAD

**Issue by Detiveu** [eritpchy/Xposed-Fingerprint-pay#2]
你好，貌似你不用play，http://pan.baidu.com/s/1eSF3Ggq，所以我传到百度云了，感兴趣的话可以看下

**Comment by eritpchy** [comment]
您好 最近没有时间更新, 不介意的话您可以用下我上传的6.5.13版本

**Comment by Detiveu** [comment]
好吧

**Comment by liberize** [comment]
@Detiveu 试试这个：
https://pan.baidu.com/s/1mhTo3PI

**Comment by eritpchy** [comment]
@liberize 不介意的话我就照着你的patch 改了?, 当然这也就没你的commit 记录了

**Comment by liberize** [comment]
等 @Detiveu 反馈吧，我没测过

**Comment by liberize** [comment]
我写了一个 shell 脚本，自动解析 apk，试了几个脚本都是可用的
https://gist.github.com/liberize/44b151b6b40a2af1716d484ccd4f8e66

**Comment by eritpchy** [comment]
@liberize 这...佩服大佬. 我准备周末改成版本无关的呢

**Comment by liberize** [comment]
直接代码自动适配，感觉还是有点难度。我对 android 不大熟悉，到是对脚本更熟悉点。期待中。

**Comment by eritpchy** [comment]
@Detiveu  Fix in  https://github.com/eritpchy/Xposed-Fingerprint-pay/commit/55a18f86abac44f1e4cbae27b931e6bd746a56b5
