### ISSUE TITLE
闲鱼客户端无法调用支付宝指纹支付

### ISSUE THREAD

**Issue by HikariCalyx** [eritpchy/Xposed-Fingerprint-pay#21]
机型：诺基亚6 国行(HMD Global Oy Nokia TA-1000)，Android 7.1.1，安全更新级别2017年11月6日。

直接在支付宝客户端下使用正常。

**Comment by eritpchy** [comment]
咸鱼是自己一套的, 跟淘宝一样, 支持计划: 待定!
