### ISSUE TITLE
弹出指纹验证窗口界面问题

### ISSUE THREAD

**Issue by DoveKi** [eritpchy/Xposed-Fingerprint-pay#22]
有时候窗口偏上方，有时候在中间，能不能固定一下窗口位置在中间

**Comment by eritpchy** [comment]
什么时候在中间 什么时候在上方呢 又是什么应用呢 请具体描述问题

**Comment by DoveKi** [comment]
像这样，好像是给密码支付框留的位置
![qq 20171116085143](https://user-images.githubusercontent.com/8667391/32868151-be13d314-caab-11e7-928e-6e4efd395ee4.png)
![qq 20171116085141](https://user-images.githubusercontent.com/8667391/32868149-bccc4676-caab-11e7-9187-85dd26c85b3b.png)

**Comment by eritpchy** [comment]
垃圾腾讯有移来移去会有体验问题 我故意那样做的！
