### ISSUE TITLE
解锁屏幕时自动调到支付宝二维码付款界面

### ISSUE THREAD

**Issue by Radar-Lei** [eritpchy/Xposed-Fingerprint-pay#23]
你好，刚开始用这个插件。版本1.3.1
指纹解锁屏幕时会自动调到支付宝二维码付款界面，如果是密码解锁就不会，这个挺困扰我的，我并不需要每次解锁手机屏幕都调到支付界面去。

**Comment by eritpchy** [comment]
您好 1.3.1版本并不支持支付宝指纹支付哦

**Comment by Radar-Lei** [comment]
@eritpchy 不好意思，说错了，是3.1.0

**Comment by eritpchy** [comment]
您好, 不知道你用的是不是正版呢?
请录像给我看看,
并上传Xposed 日志

**Comment by Radar-Lei** [comment]
@eritpchy 解决了，华为手机的问题，把自带的华为钱包的指纹支付关了就好了
