### ISSUE TITLE
疑似本模块导致island中的微信闪退

### ISSUE THREAD

**Issue by duament** [eritpchy/Xposed-Fingerprint-pay#29]
系统：omni-8.1.0-20180211-oneplus5-WEEKLY
Xposed: 90.1-beta3 (Systemless) Magisk

取消勾选本模块并重启之后，island中的微信正常

微信闪退时的日志：
[wechat_crash.log](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1722827/wechat_crash.log)

**Comment by eritpchy** [comment]
知道了, 安卓8 兼容问题

**Comment by yswtrue** [comment]
我也遇到这个问题了，坐等大佬解决，😄

**Comment by gricn** [comment]
同遇到此问题

**Comment by eritpchy** [comment]
too long
