### ISSUE TITLE
重新打开支付宝后会自动关闭指纹支付

### ISSUE THREAD

**Issue by liyafe1997** [eritpchy/Xposed-Fingerprint-pay#31]
如题，更新到3.5.0版本后，在关闭支付宝（停止运行）后再重新打开支付宝会自动关闭指纹支付，需要到设置-指纹支付中重新勾上开关。微信/QQ/淘宝一切正常。
支付宝版本 10.1.15 (From Google Play)
手机LG V20
Android 7.0
Xposed v89

**Comment by eritpchy** [comment]
没出现过, 请将你的支付宝 apk 上传上来

**Comment by liyafe1997** [comment]
[com.eg.android.AlipayGphone.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770667/com.eg.android.AlipayGphone.zip)
[com.eg.android.AlipayGphone.z06.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770677/com.eg.android.AlipayGphone.z06.zip)
[com.eg.android.AlipayGphone.z02.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770678/com.eg.android.AlipayGphone.z02.zip)
[com.eg.android.AlipayGphone.z03.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770679/com.eg.android.AlipayGphone.z03.zip)
[com.eg.android.AlipayGphone.z04.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770680/com.eg.android.AlipayGphone.z04.zip)
[com.eg.android.AlipayGphone.z05.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770681/com.eg.android.AlipayGphone.z05.zip)
[com.eg.android.AlipayGphone.z01.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/1770682/com.eg.android.AlipayGphone.z01.zip)

（只能上传小于10MB且后续是zip，只能这么传了。z01~z06要把后缀的.zip去掉方便解压）
https://pastebin.com/CHG2N20h
这个是我打开支付宝-打开设置-指纹设置，然后勾上，然后干掉支付宝，再进入设置-指纹设置的xposed log。（此时即第二次进入指纹设置里面的“启用”勾已经不在了）

**Comment by liyafe1997** [comment]
话说这个是否启用的配置是保存在哪里呢？如果您那边没法重现的话，我试着自己跟踪一下。

**Comment by liyafe1997** [comment]
更新到10.1.18（play）也没用，发现打上启用的钩后配置文件并不会添加启用的键值

**Comment by eritpchy** [comment]
知道了

**Comment by liyafe1997** [comment]
还有一个现象 ，把指纹支付在支付宝data/share_perf（大概是这个吧，就是存xml配置的那个目录）下产生的那个xml删掉，然后打开支付宝-指纹支付设密码，此时会生成这个xml并且保存密码，之后做任何更改包括改密码或者勾上启用都不会保存。也就是这个配置是一次性的，仅在创建时会写入，之后不会改。指纹支付3.6.0 支付宝10.1.18。

**Comment by eritpchy** [comment]
应该是系统问题, 暂时无解, 你可以尝试修改https://github.com/eritpchy/Xposed-Fingerprint-pay/blob/master/app/src/main/java/com/yyxx/wechatfp/util/Config.java 这个文件吧相应的数据填入, 编译个 app 自己使用

**Comment by liyafe1997** [comment]
是没法保存sharedPreferences吗

**Comment by eritpchy** [comment]
原因未知

**Comment by liyafe1997** [comment]
在你那能重现吗

**Comment by eritpchy** [comment]
不能

**Comment by liyafe1997** [comment]
我发现支付宝启动时，xposed log wehatfp会报
java.lang.ClassNotFoundException: Didn't find class "com.android.bluetooth.gatt.GattService" on path: DexPathList[[zip file "/data/app/com.eg.android.AlipayGphone-1/base.apk"],nativeLibraryDirectories=[/data/app/com.eg.android.AlipayGphone-1/lib/arm, /system/fake-libs, /data/app/com.eg.android.AlipayGphone-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
不知道是否和这个有关？另外为什么会去找bluetooth相关的东西？

**Comment by eritpchy** [comment]
理论上没影响

**Comment by liyafe1997** [comment]
我终于知道为什么了。原来我在RootCloak里面把支付宝加进去了。
