### ISSUE TITLE
另一种微信指纹支付的实现

### ISSUE THREAD

**Issue by kxzxxx** [eritpchy/Xposed-Fingerprint-pay#33]
微信指纹支付应该是得满足两个条件，一个是机型，第二个是检查机子的keystore里是否存在soter
https://github.com/LineageOS/android_device_oneplus_oneplus3/commit/34628573cbf6f069643ebcba8095d7f817bf0e68
其他的条件有没有不知道了
这个是一加3在lineageos上实现的方法
我之前移植过红米note4的支付宝指纹支付
支付宝的需要有 prebuilt的ifaadaemon 然后检查系统的boot class里是否存在 ifaa manager

**Comment by eritpchy** [comment]
暂时没时间研究, 有空你可以自己先弄

**Comment by eritpchy** [comment]
@kxzxxx  方便的话吧编译后的 APK 发上来

**Comment by eritpchy** [comment]
经测试json 部分似乎过不去
