### ISSUE TITLE
play商店版支付宝无法正常使用

### ISSUE THREAD

**Issue by JAustinal** [eritpchy/Xposed-Fingerprint-pay#34]
手持Google pixel，原生8.1，使用magisk的systemless版xposed。
指纹支付模块的3.3、3.5、3.6版本会使play商店版本的支付宝反复黑屏闪退，每次闪退后本模块保存的支付宝密码消失，处于不启用的状态。
取消勾选本模块并重启后支付宝正常，排除其他模块影响。
卸载重装过旧版本的支付宝，闪退依旧存在，并排除存储重定向的影响。
play商店版微信可正常使用。

**Comment by Narutojoy** [comment]
同，我是Google pixel 2XL，系统8.1，支付宝是play版，转账或者点朋友都会有随机的迷之闪退，几次闪退后，保存的密码就没了…

**Comment by eritpchy** [comment]
请用China版

**Comment by Narutojoy** [comment]
原来是支付宝版本问题😆

**Comment by JAustinal** [comment]
不想用国内版……

2018年3月7日 15:39，"Jason" <notifications@github.com>写道：

**Comment by Narutojoy** [comment]
我也不想用国内版～为了指纹也没办法了2333

**Comment by JAustinal** [comment]
国内版依旧存在闪退问题。

2018年3月7日 15:39，"Jason" <notifications@github.com>写道：

**Comment by JAustinal** [comment]
升级到最新play商店版就正常了（其实是我找不到支付宝的日志文件）。🌚

2018年3月8日 09:27，"Jason" <notifications@github.com>写道：
