### ISSUE TITLE
淘宝7.55，7.60版本均没有选项

### ISSUE THREAD

**Issue by leyan22** [eritpchy/Xposed-Fingerprint-pay#35]
是不是不支持新版啊，我用的3.6.0，微信，支付宝，QQ最新版一切正常！就是淘宝不行了！

**Comment by leyan22** [comment]
下载了仓库里的6.11依然没有选项！怎么解决？

**Comment by eritpchy** [comment]
xposed 问题吧 我们都正常

**Comment by leyan22** [comment]
奇怪，我把指纹支付，手机淘宝各版本安装了无数遍，均无法解决问题，淘宝始终没有选项！
