### ISSUE TITLE
希望能增加对virtualxposed支持

### ISSUE THREAD

**Issue by fenglipop29** [eritpchy/Xposed-Fingerprint-pay#36]
https://github.com/android-hacker/VirtualXposed
3.3版本能支持，新版本却没有支持virtualxposed，希望后续版本能在virtualxposed环境下使用。

**Comment by eritpchy** [comment]
知道了

**Comment by eritpchy** [comment]
https://github.com/eritpchy/Xposed-Fingerprint-pay/commit/20505c32bcf3895270fc5d58af17f5a9abad9f41
