### ISSUE TITLE
导致livedisplay失效

### ISSUE THREAD

**Issue by garr970** [eritpchy/Xposed-Fingerprint-pay#38]
有个小问题哦...
启用指纹支付模块
会导致lineage OS中
显示-livedisplay
自动调节色温
失效。（启用夜晚模式也无效）
作者可以帮忙看一下问题原因吗？

**Comment by eritpchy** [comment]
尝试吧 initGeneric 函数给禁用试试
https://github.com/eritpchy/Xposed-Fingerprint-pay/blob/master/app/src/main/java/com/yyxx/wechatfp/xposed/WalletBaseUI.java
