### ISSUE TITLE
申请支持QQ HD版本

### ISSUE THREAD

**Issue by Gokou-Ruri** [eritpchy/Xposed-Fingerprint-pay#40]
![screenshot_20180426-152853](https://user-images.githubusercontent.com/26711804/39291741-9413b6da-4966-11e8-8a2c-9ff44e0faf4c.png)
![screenshot_20180426-152857](https://user-images.githubusercontent.com/26711804/39291742-945ff766-4966-11e8-8d73-4834733a71ba.png)

**Comment by eritpchy** [comment]
已收到

**Comment by eritpchy** [comment]
原生不支持指纹的应用我们不会支持!
