### ISSUE TITLE
请问能否支持天猫和京东app内支付？

### ISSUE THREAD

**Issue by Gokou-Ruri** [eritpchy/Xposed-Fingerprint-pay#46]
因为天猫app有些专属的券和活动，所以经常购物的话基本这个也是必装。
京东app好像也不支持。
请问后续能支持天猫和京东app吗？
话说play版qq(6.6.7)本身不支持Android的指纹API，能让Xposed-Fingerprint-pay对指纹进行验证然后执行支付行为吗？

**Comment by eritpchy** [comment]
必须支持指纹 API 才会支持!

**Comment by eritpchy** [comment]
@nde123456 目前并没有支持京东支付

**Comment by Gokou-Ruri** [comment]
@eritpchy 咸鱼(v6.1.8)、1688(v7.12.0.0)、天猫(v7.11.10)已经支持Android指纹API了。（截图上没显示天猫，因为装在另一台手机上。）具体从哪个版本开始不清楚，至少现在都支持了。
p.s.以上均为play版。
![screenshot_20180902-224925](https://user-images.githubusercontent.com/26711804/44957253-c08c0f80-af02-11e8-88d9-86ccc34b22b4.png)

**Comment by eritpchy** [comment]
好的

**Comment by eritpchy** [comment]
没有精力适配更多app, 不支持
