### ISSUE TITLE
设置丢失

### ISSUE THREAD

**Issue by RuioWolf** [eritpchy/Xposed-Fingerprint-pay#50]
很多时候不知道什么时候设置就丢了 要输密码才发现模块的设置丢了这样子。。Pixel2XL 8.1 因为8.1的Xposed导致支付宝有时候闪退所以使用前会先用lucky patcher把支付宝odex化

**Comment by eritpchy** [comment]
https://github.com/eritpchy/Xposed-Fingerprint-pay/issues/31
这个问题无法复现, 如有能力请尝试自行解决
