### ISSUE TITLE
支持微信6.6.7 play(1303)吗

### ISSUE THREAD

**Issue by jzw3131** [eritpchy/Xposed-Fingerprint-pay#51]
微信6.6.7 play(1303)，在分身大师中微信打开没有指纹设置

**Comment by eritpchy** [comment]
![20180824_190139](https://user-images.githubusercontent.com/8630635/44581511-933bb500-a7d0-11e8-9498-25af4e6fa501.jpg)
![20180824_190146](https://user-images.githubusercontent.com/8630635/44581513-959e0f00-a7d0-11e8-86c5-1254daf95612.jpg)
经过测试并没有问题
