### ISSUE TITLE
偶尔设置丢失

### ISSUE THREAD

**Issue by HankAviator** [eritpchy/Xposed-Fingerprint-pay#52]
3.8.0版本开始，偶尔会发生设置丢失，支付宝已储存的密码被删除。请问本软件的设置存储在哪个位置？

**Comment by Gokou-Ruri** [comment]
在对应的支付或购物app的数据目录。

**Comment by eritpchy** [comment]
3.8.0并没有触碰到这部分代码, 这个问题比较奇怪, 而且我这里无法复现, 建议自己查一下
