### ISSUE TITLE
关于各app设置入口的建议

### ISSUE THREAD

**Issue by mlgexyz** [eritpchy/Xposed-Fingerprint-pay#56]
现版本的指纹功能管理都在各APP的设置界面中，能否在_指纹支付_的本体界面也添加一个设置的入口呢？主要是因为一些第三方修改的QQ包无法显示指纹设置入口，但是模块以及正常加载了，这样子无法开启和关闭就有点难受。

**Comment by eritpchy** [comment]
不能
