### ISSUE TITLE
能不能把你模块支持的微信放出来,放网盘或者git都行

### ISSUE THREAD

**Issue by javaeryang** [eritpchy/Xposed-Fingerprint-pay#6]
自己尝试下载编译,下载源码,用as打开以后,好多错误,提示有一个zip下载失败,被墙的原因,你用的貌似是用3.0最新版的AS吧,我的还是2.3.1,然后以后再改,需要你支持的微信,希望能放出来,谢谢

**Comment by eritpchy** [comment]
版本从来不是问题! 熟悉gradle就自己改吧!
