### ISSUE TITLE
关于微信支付使用指纹支付时的问题

### ISSUE THREAD

**Issue by Aooccll** [eritpchy/Xposed-Fingerprint-pay#64]
机型:小米6  系统:安卓8.1   lineageOS   。在使用按home键读取指纹时会返回到桌面以至于无法使用指纹支付。支付宝指纹支付正常但是如果能优化一下支付宝指纹支付时的UI就更好了

**Comment by eritpchy** [comment]
抱歉我没有小米6, 如果有条件, 请自己尝试一下解决问题
