### ISSUE TITLE
支付宝输入密码不全

### ISSUE THREAD

**Issue by daiaji** [eritpchy/Xposed-Fingerprint-pay#65]
就这样
![screenshot_20181216-093926 2](https://user-images.githubusercontent.com/25875791/50049131-f5218100-0117-11e9-8bdf-5970336c7c58.png)

**Comment by eritpchy** [comment]
没出现过这种情况, 很有可能是你输入的密码本身就不够位数

**Comment by daiaji** [comment]
@eritpchy 找了一圈 是 Text Aide模块的问题 这么说支付宝密码输入是模拟屏幕触摸输入？
能直接hook吗？

**Comment by eritpchy** [comment]
不打算改底层
