### ISSUE TITLE
请求适配支持 work profile 的指纹对接

### ISSUE THREAD

**Issue by NewBugger** [eritpchy/Xposed-Fingerprint-pay#66]
edit:
因为微信这类毒瘤很多会拿着 storage 权限为所欲为，把微信安装到 work profile（例如 island 这类软件）
要是作者大大能适配非 0 用户的指纹验证就好了
work profile 的用户 id 一般从 10 开始取；而 owner 的 id 就是 0

---------------------------------------------------------------------------------------
fingerprint verification has been closed by system

我已经查过微信和模块程序的相关权限都没关闭

系统 Lineageos 15.1 Oreo，微信 play 6.6.7 但是其它例如淘宝也报错所以应该不是微信版本的问题

![806025113_138550](https://user-images.githubusercontent.com/41441631/50883994-a1f3d300-1424-11e9-91ec-68c0c33bb85a.jpg)

**Comment by eritpchy** [comment]
有做过适配, 效果堪忧
