### ISSUE TITLE
和mback不兼容

### ISSUE THREAD

**Issue by hanshenwansui** [eritpchy/Xposed-Fingerprint-pay#67]
mback按上去后返回 无法使用指纹

**Comment by eritpchy** [comment]
抱歉, 我没有 mback 的设备

**Comment by hanshenwansui** [comment]
呃呃，那啥  能不能设置一下 支付时关闭mback啊。。。魅族指纹少

**Comment by hanshenwansui** [comment]
尤其喜欢flyme  谢谢大佬啦

**Comment by eritpchy** [comment]
魅族在支付的时候已经关闭 mback 了
这应该是魅族的 bug, 没有机子我也不能解决

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by hanshenwansui** [comment]
嗯嗯，谢谢大佬啦  
学生党表示没法给你寄一个。。
那那那，大佬新年快乐

**Comment by eritpchy** [comment]
too long
