### ISSUE TITLE
DIDI  Coudn't Pay

### ISSUE THREAD

**Issue by rp4k** [eritpchy/Xposed-Fingerprint-pay#70]
i couldn't pay in didi today when i tried to use it.. my payment would fail if i selected  alipay or wechat pay.   i had to disable your xposed module and then reboot the phone to pay for didi.

**Comment by eritpchy** [comment]
1. Screen recording?
2. Have you input correct payment password in Settings->Fingerprint-pay?
3. try Magisk Fingerprint-pay https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/?

**Comment by eritpchy** [comment]
[1556415608388506.mp4.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/3124502/1556415608388506.mp4.zip)

**Comment by rp4k** [comment]
no screen recording..   if you want you can add my wechat to try to help me solve. i love your work . (rp4000在微信)  i have only installed your app through  EdXposed framework i am on S10+ SM-G975F  do you recommend that i uninstall  from EdXposed and install Directly through MagiskManager?

**Comment by rp4k** [comment]
Should i try to manually install the magisk module i do not see them in magisk manager.    i use  alipay, wechatpay and taobao. didi, waimai

**Comment by eritpchy** [comment]
yes manually

**Comment by rp4k** [comment]
can you send me the modules manually.  i just tried to install it again from xposed. now my s10 wont even respond to touch.

**Comment by eritpchy** [comment]
https://github.com/RikkaApps/Riru/releases/download/v18/magisk-riru-core-v18.zip
https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/releases/download/3.9.3/magisk-riru-module-xfingerprint-pay-wechat-v3.9.3.zip

**Comment by rp4k** [comment]
i did that, i installed  alipay version,  wechat version, taobao version.

**Comment by rp4k** [comment]
alipay version is 3.9.2   when i check update it says "network error"

**Comment by eritpchy** [comment]
Is OK?

**Comment by rp4k** [comment]
i wont try didi until tomorrow. or tonight.  i only use it once a day at most.  i will let you know.  could i add your wechat?

**Comment by eritpchy** [comment]
eritpchy
