### ISSUE TITLE
如何彻底卸载

### ISSUE THREAD

**Issue by cofedream** [eritpchy/Xposed-Fingerprint-pay#72]
我已经卸载了。但是支付的时候还是会被调用

**Comment by cofedream** [comment]
![截图1](https://gitee.com/cofedream/NoteData/blob/master/images/temp/Screenshot_20190510-132819.jpg)
![截图2](https://gitee.com/cofedream/NoteData/blob/master/images/temp/Screenshot_20190510-132930.jpg)

**Comment by eritpchy** [comment]
要走我可不会帮你
