### ISSUE TITLE
开启微信指纹支付，商场停车泊时易支付界面显示调取微信模块失败

### ISSUE THREAD

**Issue by ForeverLive** [eritpchy/Xposed-Fingerprint-pay#73]
关了指纹支付就OK

**Comment by eritpchy** [comment]
xposed日志上传一下
易支付 支付二维码来一个

**Comment by ForeverLive** [comment]
> xposed日志上传一下
> 易支付 支付二维码来一个

用的EdXposed，刚才才发现日志竟然无法读取。。我找时间去重新去停一次看看

**Comment by ForeverLive** [comment]
> xposed日志上传一下
> 易支付 支付二维码来一个

另外有个小问题，取消支付后指纹识别那个小图标还在需要我指纹确认一次才消失，并不会因为取消支付而一起消失，手机一加7PRO，系统版本9.5.3

**Comment by eritpchy** [comment]
too long
