### ISSUE TITLE
忘记密码了

### ISSUE THREAD

**Issue by lupohan44** [eritpchy/Xposed-Fingerprint-pay#78]
有办法找回密码吗

**Comment by eritpchy** [comment]
没有

**Comment by lupohan44** [comment]
成功找回密码
/app/src/main/java/com/yyxx/wechatfp/xposed/plugin/XposedWeChatPlugin.java该文件169行前插入一行 Toast.makeText(context, pwd, Toast.LENGTH_SHORT).show();
编译(没环境的可以用gitee的在线编译) 安装后随便给人转0.01 用指纹后就会用toast显示密码
