### ISSUE TITLE
支付宝代付页面同时出现原应用的密码输入

### ISSUE THREAD

**Issue by yipsama** [eritpchy/Xposed-Fingerprint-pay#81]
我用支付宝帮别人代付的时候，会同时出现要求输入指纹和输入密码的界面。
但认证指纹之后就会显示必须手动输入密码。
支付宝版本 10.1.87

**Comment by yipsama** [comment]
我这里只在当面扫码代付的时候会出现

**Comment by gxy8221450** [comment]
我这里饿了吗吊起支付宝付款也出现这样情况

**Comment by HankAviator** [comment]
生活缴费时也是如此，密码输入界面在最上方，指纹验证在下一级。

**Comment by eritpchy** [comment]
请更新至3.9.8

**Comment by HankAviator** [comment]
已经是3.9.8了，支付宝 10.1.87.7347

**Comment by yipsama** [comment]
同3.9.8，连普通的代付都变成只有密码支付没有指纹了

**Comment by eritpchy** [comment]
录像看看， 版本号也要录进去

**Comment by HankAviator** [comment]
[ScreenRecord-2020-03-04-23-44-30_1.zip](https://github.com/eritpchy/Xposed-Fingerprint-pay/files/4288494/ScreenRecord-2020-03-04-23-44-30_1.zip)

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Xposed-Fingerprint-pay/commit/463ab22318b4a9622381bb730fde7dd6cc46b65d

**Comment by eritpchy** [comment]
@HankAviator  由于没有帐号测试长密码仍然有可能不支持

**Comment by HankAviator** [comment]
@eritpchy 长密码不支持，已经改成短的了，短的没问题。
