### ISSUE TITLE
能否支持pixel4/pixel4xl的人脸支持

### ISSUE THREAD

**Issue by OCD0711** [eritpchy/Xposed-Fingerprint-pay#86]
能否支持pixel4/pixel4xl的人脸支持, fingerface的方式可以集成么?

**Comment by eritpchy** [comment]
可以的，给我来台pixel4xl

**Comment by Hal1ucinogen** [comment]
> 可以的，给我来台pixel4xl

把对 FingerprintManager 的调用换成 BiometricManager 和 BiometricPrompt 即可。
官方的 Biometric 支持人脸、虹膜及指纹等，对原有的 FingerprintManager 做了兼容。
具体可以参考 [FingerFace](https://github.com/topjohnwu/Fingerface)。
其实现在同时用你当前模块加上 FingerFace 也能用，但是要装两个始终不爽，且强制依赖 Xposed，导致不能直接只用您对应的 Riru 模块。您看能不能麻烦适配一下。

**Comment by Hal1ucinogen** [comment]
> 可以的，给我来台pixel4xl

抱歉，看了下代码您这边调用的是 FingerprintIdentify 这个库，看来应该需要那边适配才是。

**Comment by eritpchy** [comment]
不支持
